### ISSUE TITLE
Need Improvement

### ISSUE THREAD

**Issue by vishalxtyagi** [Richard1407/Custom-Search#1]
## Issue Description
To create a proper application, the code must be improved. 

## Task List
- [ ] The codes must be broken into parts. 
- [ ] Avoid utilising commenting codes whenever possible. 
- [ ] File names should make sense, otherwise you may just use `main.py` for python files
